remote_theme: pages-themes/merlot@v0.2.0
plugins:
title: Jake Johnson
description: Personal Portfolio of Phillip "Jake" Johnson
show_downloads: false
google_analytics:
github:
  is_user_page: false
  is_project_page: false
  # repository_url: http://example.com/download.zip
  # another_url: another 
