remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Jake Johnson
description: Welcome to the personal portfolio of Phillip "Jake" Johnson!
